### ISSUE TITLE
BOM/Capacitors type question.

### ISSUE THREAD

**Issue by dbychkov** [TomMajor/ZX-Spectrum-Adventure-2020#1]
Hi Tom,

Do I have to use low impedance/ESR capacitors to build a Superfo Harlequin 48k/128k computer?
Do you think the general purpose aluminum electrolytic caps will also work?
Do you know if the 74HTC logic can be used instead of 74HC?

===
Thanks.
Dmitriy

**Comment by TomMajor** [comment]
Hi Dmitriy,
I usally go for high quality, low ESR, high temperature caps like in my BOM - for quality and endurance reasons.
In this special case, I thing C3 and C5 should be low ESR because of the DC-DC switching converter, the others can be general purpose.

As for HCT/HC questions, please ask this here:
https://forum.tlienhard.com/phpBB3/viewtopic.php?f=6&t=981
Is mainly German, but English will be answered there as well.
Look for user ingo, he has great insight in the Superfo Harlequin, did even some improvements for Rev. G. and he can answer this right away I would guess.
